# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://github.com/federico-terzi/espanso

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from you shell"

  # Emojis
  - trigger: ":lol"
    replace: "😂"
  - trigger: ":llol"
    replace: "😂😂😂😂"
  - trigger: ":sad"
    replace: "☹"
  - trigger: ":ssad"
    replace: "☹☹☹☹"

  # Accented letters
  - trigger: "e''"
    replace: "è"
  - trigger: "e//"
    replace: "é"
  - trigger: "a''"
    replace: "à"
  - trigger: "i''"
    replace: "ì"
  - trigger: "o''"
    replace: "ò"
  - trigger: "u''"
    replace: "ù"

  # Capital accented letters
  - trigger: "E''"
    replace: "È"
  - trigger: "E//"
    replace: "É"