# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          sudo apt -y update
          sudo apt install -y libxtst-dev libx11-dev libxdo3 libxdo-dev
        displayName: Install library dependencies
      - template: ci/test.yml
      - template: ci/build-linux.yml
#      - template: ci/deploy.yml

#  - job: macOS
#    pool:
#      vmImage: 'macOS-10.13'
#    steps:
#      - template: templates/npm-steps.yml  # Template reference
#
#  - job: Windows
#    pool:
#      vmImage: 'vs2017-win2016'
#    steps:
#      - script: echo This script runs before the template's steps, only on Windows.
#      - template: templates/npm-steps.yml  # Template reference
#      - script: echo This step runs after the template's steps.