[package]
name = "espanso"
version = "0.1.0"
authors = ["Federico Terzi <federicoterzi96@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
widestring = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "2.0.2"
clap = "2.33.0"
regex = "1.3.1"
log = "0.4.8"
simplelog = "0.7.1"
zip = "0.5.3"
fs2 = "0.4.3"
serde_json = "1.0.40"

[target.'cfg(unix)'.dependencies]
libc = "0.2.62"


[dev-dependencies]
tempfile = "3.1.0"

[build-dependencies]
cmake = "0.1.31"