[package]
name = "espanso"
version = "0.1.0"
authors = ["Federico Terzi <federicoterzi96@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
widestring = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "2.0.2"

[build-dependencies]
cmake = "0.1.31"