name: espanso
version: 0.4.1
summary: A Cross-platform Text Expander written in Rust
description: TODO

confinement: strict
base: core18

parts:
  espanso:
    plugin: rust
    source: .
    build-packages:
     - libssl-dev
     - pkg-config
     - cmake
     - libxtst-dev
     - libx11-dev
     - libxdo-dev
    stage-packages:
     - libx11-6
     - libxau6
     - libxcb1
     - libxdmcp6
     - libxdo3
     - libxext6
     - libxinerama1
     - libxkbcommon0
     - libxtst6
     - libnotify-bin
     - xclip

apps:
  espanso:
    command: bin/espanso
    plugs:
     - x11
     - network-bind
     - desktop
