[package]
name = "espanso-detect"
version = "0.1.0"
authors = ["Federico Terzi <federico-terzi@users.noreply.github.com>"]
edition = "2018"
build="build.rs"

[dependencies]
log = "0.4.14"
lazycell = "1.3.0"

[target.'cfg(windows)'.dependencies]
widestring = "0.4.3"

[build-dependencies]
cc = "1.0.66"

[dev-dependencies]
enum-as-inner = "0.3.3"